import type { Metadata } from "next";
import { PolicyShell } from "@/components/policy-shell";
import { siteConfig } from "@/lib/site-config";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "How Meridian Repute collects, uses, and protects personal information across our website, consultations, and reputation intelligence services.",
  alternates: { canonical: "/privacy-policy" },
};

export default function PrivacyPolicyPage() {
  return (
    <PolicyShell title="Privacy Policy" lastUpdated="15 July 2026">
      <p>
        Meridian Repute (&ldquo;we&rdquo;, &ldquo;our&rdquo;, &ldquo;us&rdquo;)
        is an AI reputation intelligence and executive influence consultancy
        based in Lahore, Pakistan. Discretion is central to our work, and this
        policy explains what personal information we collect through our website
        and services, how we use it, and the choices available to you.
      </p>

      <h2>1 — Information We Collect</h2>
      <p>
        <strong>Information you provide directly.</strong> When you submit our
        consultation form, contact us by email, phone, or WhatsApp, or engage
        our services, we may collect your name, email address, phone number,
        company name, role, and the details of your enquiry.
      </p>
      <p>
        <strong>Information collected automatically.</strong> Like most
        websites, we collect limited technical data such as IP address, browser
        type, device information, pages visited, and referral source through
        cookies and analytics tools. This helps us understand how visitors use
        the site and improve it.
      </p>
      <p>
        <strong>Information gathered during engagements.</strong> If you become
        a client, our services involve researching publicly available
        information about you or your organisation — search results, news
        coverage, social media profiles, reviews, and responses generated by AI
        systems. We collect this information only with your authorisation, only
        from public or lawfully licensed sources, and only for the purpose of
        delivering the services you have engaged us for.
      </p>

      <h2>2 — How We Use Information</h2>
      <ul>
        <li>To respond to enquiries and schedule consultations.</li>
        <li>
          To deliver reputation audits, AI visibility reports, executive
          branding, monitoring, and related services.
        </li>
        <li>
          To administer client engagements, invoicing, and contractual
          obligations.
        </li>
        <li>To improve our website, services, and communications.</li>
        <li>To comply with legal obligations under the laws of Pakistan.</li>
      </ul>
      <p>
        We do not sell personal information. We do not use client engagement
        data for advertising.
      </p>

      <h2>3 — Cookies &amp; Analytics</h2>
      <p>
        Our website uses essential cookies required for the site to function and
        analytics cookies that help us measure traffic. You can disable cookies
        through your browser settings; the site will remain usable, though some
        features may not work as intended. Analytics data is aggregated and is
        not used to identify individual visitors.
      </p>

      <h2>4 — WhatsApp &amp; Third-Party Services</h2>
      <p>
        If you contact us through WhatsApp, email, or a scheduling link, your
        information is also processed by those providers under their own privacy
        policies. We use reputable third-party providers for hosting, email,
        analytics, and scheduling, and we share only the information necessary
        for them to perform their function.
      </p>

      <h2>5 — Confidentiality of Client Work</h2>
      <p>
        Reputation work involves sensitive information. All client engagements
        are covered by a written consulting agreement and, where requested, a
        non-disclosure agreement. We do not disclose the identity of our
        clients, the existence of an engagement, or any material shared with us,
        except with the client&apos;s written consent or where required by law.
      </p>

      <h2>6 — Data Retention &amp; Security</h2>
      <p>
        We retain personal information only as long as necessary for the
        purposes described above, to meet contractual and legal requirements,
        and to maintain business records. We apply reasonable technical and
        organisational safeguards — including access controls and encrypted
        storage — to protect the information we hold. No method of transmission
        or storage is entirely secure, and we cannot guarantee absolute
        security.
      </p>

      <h2>7 — Your Rights</h2>
      <p>
        You may request access to the personal information we hold about you,
        ask us to correct inaccuracies, or ask us to delete information that we
        are not legally or contractually required to retain. You may also opt
        out of non-essential communications at any time. To exercise any of
        these rights, contact us using the details below.
      </p>

      <h2>8 — Legal Basis &amp; Governing Law</h2>
      <p>
        We process personal information in accordance with the applicable laws
        of Pakistan, including the Prevention of Electronic Crimes Act (PECA) as
        amended, and we monitor developments in Pakistani data protection
        legislation. This policy is governed by the laws of Pakistan.
      </p>

      <h2>9 — Changes to This Policy</h2>
      <p>
        We may update this policy from time to time. The &ldquo;Last
        updated&rdquo; date above reflects the most recent revision. Material
        changes will be posted on this page.
      </p>

      <h2>10 — Contact</h2>
      <p>
        Meridian Repute · Lahore, Pakistan
        <br />
        Email: <a href={`mailto:${siteConfig.email}`}>{siteConfig.email}</a>
        <br />
        Phone / WhatsApp: +92 333 4723813
      </p>
    </PolicyShell>
  );
}
